### ISSUE TITLE
"A fun-filled new take on the casual first-person arena shooter. is not responding"

### ISSUE THREAD

**Issue by nyuszika7h** [red-eclipse/base#114]
Not sure why it says that, but it would be nice if it just said "Red Eclipse" instead.

**OS:** Windows 8.1
**Red Eclipse version:** 1.5.0

**Comment by qreeves** [comment]
Incomprehensible.

**Comment by TheLastProject** [comment]
@nyuszika7h When making bug reports, please add as much information as you can, so we are able to understand the issue. This information included, but is not limited, to your Operating System, Red Eclipse version, and whatever else could help understanding the issue (screenshots are often useful too).

**Comment by Calinou** [comment]
He's likely talking about the Windows crash message.

**Comment by qreeves** [comment]
OK, just CBF chasing up these ill thought up items myself. We need a contributing.md still.

**Comment by freezurbern** [comment]
I know where this is from! It is something to do with the new information (sometimes shown in the task manager under description) that the Windows binaries are getting. I think the version.h or redeclipse.rc file is where this comes from. I know we talked about it in IRC because someone saw this string of text in their task manager.

---

Okay, what I'm trying to say is that when Windows presents the not-responding dialog, it is using this big long string instead of the game name. SO changing the string to just Red Eclipse somewhere (either of those two files, i'm not sure) would fix this. And I believe this is a valid issue that should probably be fixed to help people not get confused.

**Comment by acerspyro** [comment]
> The little things

**Comment by shirepirate** [comment]
https://github.com/red-eclipse/base/commit/3fe0f65ddbcdae2c6cbf87ec2d8fc95717061f08

**Comment by qreeves** [comment]
The commit that supposedly fixed this is implemented incorrectly.

**Comment by shirepirate** [comment]
https://github.com/red-eclipse/base/commit/b9d9e95e329513f0ce1621236b7cdc2462ca7d8b
