### ISSUE TITLE
Variable menu: checkboxes for bitwise variables.

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#126]
A very useful enhancement (and bringing back a part of the past) would be to have checkboxes for the variables that take a bitwise value. ~~The GUI could scan the usage descriptions if they were in a common format, finding what values should be shown.~~

**Comment by qreeves** [comment]
A new parameter would probably be a better idea than trying to parse the long description.

**Comment by bonifarz** [comment]
Yeah, I thought of that a while ago, but parsing descriptions will not work well here (a first attempt was quite useless). As an unofficial modification, you could add some bitfields with generic labels (e.g. as in the comment line for flags in the vars menu), but that's an ugly hack.

**Comment by bonifarz** [comment]
Hey @freezurbern, here's sort of a work-around for this:
https://github.com/red-eclipse/community/blob/master/bonifarz/vars.cfg
This checks if the variable's max value takes the form 2^n -1 and displays bitfields accordingly.
Since I exclude hex (colour) values, this one is based on #239 

I guess a clean solution would still need a new flag for bitlist vars and a nicer way to show the usage instructions, but this seems to work okay for now :smiley:

**Comment by bonifarz** [comment]
I think you can keep the issue open as a feature request (enhancement) in the sense that we could use a flag to identify bitlist vars and maybe better usage instructions to extract bitfield labels. But I'm glad if my workaround helps a bit.

**Comment by qreeves** [comment]
@bonifarz I replaced the last field ("usage") with a general "fields" array. It uses explodelist to break down the string into pieces the same what it evaluates code (so []() etc are reserved keywords now).

Example:

`setdesc (concatword $w collide $m) "determines collision properties for a projectile from each firing action (bitwise OR)" "COLLIDE_TRACE COLLIDE_PROJ COLLIDE_OWNER IMPACT_GEOM IMPACT_PLAYER IMPACT_SHOTS BOUNCE_GEOM BOUNCE_PLAYER BOUNCE_SHOTS DRILL_GEOM DRILL_PLAYER DRILL_SHOTS STICK_GEOM STICK_PLAYER"`

Gives:
![20160129030349](https://cloud.githubusercontent.com/assets/3297929/12652047/ef2c10e2-c634-11e5-8ede-766bdc7e2960.png)

**Comment by bonifarz** [comment]
Looks nice... so, lot's of changes in usage.cfg. Will have a closer look later.

**Comment by qreeves** [comment]
Yeah, part of why I haven't closed this issue yet.

**Comment by bonifarz** [comment]
Sure thing. 
I'll add some related observations here instead of opening more issues for presumably trivial bugs:
* segfault when using `getvarfields` with a string that is no valid variable or command
* the list in the variables menu is no longer sorted alphabetically, no clue why

I tested an awkward workaround for the vars menu (line 228):
`                 scurusage = (loopconcat i (getvarfields $scurvar) [result (getvarfields $scurvar $i)])`
I'm sure we can do better than that :smiley:

**Comment by qreeves** [comment]
Both those should be fixed now :smile_cat:

**Comment by bonifarz** [comment]
I'll see if i can enhance the vars menu, such that checkboxes for bitfields are each labeled with the corresponding getvarfield entry.

**Comment by bonifarz** [comment]
So, all we need to close this is to check usage.cfg for missing field descriptions, right?
That is, if above commit is okay. And thanks my new permissions.

**Comment by qreeves** [comment]
Yep. Happy pushing.
