### ISSUE TITLE
Drones go through walls

### ISSUE THREAD

**Issue by Teddypig** [red-eclipse/base#129]
I noticed that no matter what I do, drones go through walls on my map. I asked people and no one knows, so I'm assuming a bug.

**Comment by freezurbern** [comment]
Kinda vague, wanna provide a map, demo, video?

**Comment by Jigoku** [comment]
Vague, but i think i know what's up, as it happened a few times.

If i remember rightly, quin stated a while ago that AI actors may "jump" through geometry in the case it can't find a route to a certain waypoint. If your map doesn't have waypoints, that could be the reason.

When you spawn, (and the map has no waypoints), the moment you start moving you are dropping waypoints that the bots/actors will follow.

So lets say you created a boxed off room with a few waypoints created by moving around in the room, and there are drone spawns outside of the room, they will first try to run to that waypoint, hitting the wall but when the wall blocks them, they will "teleport" to those waypoints after a certain period to stop the AI getting stuck.

EG: If an actor such as a grunt/drone cannot find a path to the next waypoint, due to something being in the way, it will teleport to the nearest available waypoint. Hence going through the wall.

To get around this, you want to drop waypoints across all possible routes in the map.
See: http://redeclipse.net/wiki/Waypoints

**Comment by qreeves** [comment]
Answered correctly by @Jigoku
