### ISSUE TITLE
noclip material bugs

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#168]
o.O Iam soo confused, we are using noclip sooo long and still there are bugs. (ok one is known i think)

1st:
The known one.
If you stand in a noclip block and in 3rd view you see how it should, but in first person you can still see your feets :O  (show screenshots)

![20150425210117](https://cloud.githubusercontent.com/assets/10883690/7334263/d61df92a-eb8e-11e4-8104-8007b42da16a.png)
![20150425210120](https://cloud.githubusercontent.com/assets/10883690/7334264/dae355d6-eb8e-11e4-85ae-f6e70805d2df.png)

2nd:
flammer bug in noclip. Sometimes! when you crouch in a noclip and flammer yourself you get no damage and catch no fire, same situation outside and you catch fire and get damage so its a noclip problem. (show screenshots)

![20150425205744](https://cloud.githubusercontent.com/assets/10883690/7334269/ebb2c626-eb8e-11e4-8dd7-b198ef5da821.png)
![20150425205740 0001](https://cloud.githubusercontent.com/assets/10883690/7334270/ebb42fde-eb8e-11e4-9ba5-61fb02142f87.png)

**Comment by IceflowRE** [comment]
And i test it in edit mode.

Oh and just a hint but i think its not so easy to repair, but the particles only works up and down and not on the side.
![20150425212428](https://cloud.githubusercontent.com/assets/10883690/7334398/a39c3428-eb91-11e4-995d-aa364bc6e574.png)

**Comment by shirepirate** [comment]
the first is not an issue, it simply means the player camera view is inside of the no-clip (the camera in 1st person mode is not at the head or eyes of the model).

the second may perhaps be a bug, but it is not an important one (there are maps in the rotation with large blocks of no-clip as in these screenshots. this is generally not acceptable for official maps). it also might not have anything to do with no-clip. there are occasional instances i've experienced where flamer, grenades & mines have not inflicted any self damage when they obviously should have (such as cooking a grenade too long, it exploding yet inflicting no self damage at all).

i don't understand your 3rd point. if you're talking about the ability to rotate particle entities, this is simple and definitely possible. if you're talking about the charred aftermath of the flamer particles not showing on vertical surfaces, this is not a very important issue either (blend maps do not work on vertical surfaces either, and that is a much more important improvement).

these are examples of things you should have discussed at the forum first before opening an issue.

**Comment by qreeves** [comment]
1. The avatar being viewed will always be rendered "on top" of everything else. This is so you can always see your player model (in reality, guns, etc stick outside the hitbox and extend into walls when pressed up against them). This is intentional and won't be fixed.

2 & 3. It is highly discouraged to use clip/noclip material in this fashion. These materials are there only to help smooth out geometry features so that the player doesn't hang/catch on them in-game. As everyone may have noticed, projectiles ignore these materials, so what you are really doing is firing inside a wall and the game is correctly saying it can't do that and kills it without letting it do damage.
