### ISSUE TITLE
Finish map CRC locks

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#242]
The current implementation for *crclock* was written to be backward compatible. For optimal use, it would help to inform the client of the map CRC being requested so they can load a local copy, if available. Also add a waiting state to signify the map is waiting to be downloaded.

**Comment by shirepirate** [comment]
the basic premise is working well, the functionality seems OK for the most part (sometimes getmap likes to not work inexplicably)

i made a little GUI tidbit example that should probably be implemented in some shape or form in the future. this GUI would be shown if a player connects and doesn't have a local copy of the map, instead of a blank screen (or loadout selection appearing, that shouldn't happen either). it would also be shown if the player does have a local copy but it is verified that the CRC do not match. instead of loading up the local map, a blank screen with this menu would be shown instead.
```
mapfetch = 0
mapdownload = 0
haslocalmap = 0
keepmaps = 0

newgui mapload [
    guiheader "loading map..."
    guistrut 0.5
    if (= $haslocalmap 0) [
        guicenter [ guitext "It seems you do not have a local copy of the map." ]
    ] [
        guicenter [ guitext "It seems the server version of the map is different from your version." ]
        guistrut 0.25
        guicenter [ guitext (format "Your map version: ^fs^fg%1^fS | Server map version:^fs^fg%2^fS" $localcrc $servercrc) ]
    ]
    guistrut 0.25
    guicenter [ guitext "Your client will now attempt to get a copy of the correct map." ]
    guistrut 1
    if (= $mapfetch 1) [
        guifont "emphasis" [ guicenter [ guitext "^fzwyrequesting map from server...^fa" ] ]
    ]
    if (= $mapdownload 1) [
        guifont "emphasis" [ guicenter [ guitext "^fzwgdownloading map from server...^fa" ] ]
    ]
    if (& (= $mapfetch 0) (= $mapdownload 0) ) [
        guifont "emphasis" [ guicenter [ guitext "^fzwrno progress...^fa" ] ]
    ]
    guistrut 1
    guicenter [
        guibutton "^fs^fgRetry^fS" [getmap]
        guistrut 1.75
        guibutton "^fs^fgReconnect^fS" [reconnect]
        guistrut 1.75
        guibutton "^fs^fgDisconnect^fS" [disconnect]
    ]
    guistrut 1
    guicenter [ guicheckbox " cache a local copy of each new map version for future use" keepmaps 1 ]
    guistrut 0.5
]
```
this is simply on-the-surface stuff so everyone understands what is happening better when a map is fetched. the aliases used are just ideas of course, i don't have an understanding and didn't bother to look at how crclock is implemented, but i have a hunch they could probably all be used if the code was properly written (some may need to be created as string variables, also the various stages of getmap would need to update a variable of it's progress, as is currently displayed in console).

**Comment by qreeves** [comment]
Yeah, mostly requires that the server informs the client of the current state. Protocol changes needed.

**Comment by bonifarz** [comment]
Thanks, @shirepirate. This is a very interesting topic, and your menu will help to learn more about this.
