### ISSUE TITLE
./redeclipse.sh and ./bin/update.sh give different bins, and one of them crashes my system.

### ISSUE THREAD

**Issue by Danfun64** [red-eclipse/base#397]
./redeclipse.sh and ./bin/update.sh provide different red eclipse binaries on my amd64 system. the one provided on ./redeclipse.sh crashes my system because it gives shader errors, while the one from ./bin/update.sh works fine. Where does the discrepancy come from?

**Comment by qreeves** [comment]
In future, please use the forum for unconfirmed errors and questions, the issue tracker is for approved bugs and features only.

The issue is you shouldn't run update.sh by itself (and I have no idea why you did) as it relies on environment variables and a proper current working directory. You'll need to delete the whole thing and start again, as you've probably messed things up beyond repair.

If you continue to have issues, post your log on the forums with info on your OS and hardware.
