### ISSUE TITLE
grenade throw issue

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#443]
behavior:
grenades, unlike the other weapons, are held only with the right hand and held farther off to the right of the player model

problem:
when standing near a wall on your right-hand side, the grenade will unnaturally stick to the wall instead of being thrown to where the crosshair is aiming. this happens in first or third person. this happens in both the primary and secondary attack. in primary, the grenade will start off it's trajectory inside of the wall and it's speed will be so greatly slowed down it will appear to have stuck inside of (or on) the wall. in secondary, the grenade starts it's trajectory a little further back for some reason and will become stuck to the wall a good distance behind the player.

solution:
the grenade needs to start it's trajectory closer to the center of the player model, even if that is not what is visually seen

**Comment by shirepirate** [comment]
this problem still persists:

https://www.youtube.com/watch?v=pMQmGBa7wkg

perhaps it wasn't fixed in the best way? frankly i don't even know how it was fixed

**Comment by qreeves** [comment]
The message I typed on the phone didn't work.. Anyway, the issue is more with the animation than anything, the weapon `timedelay` variable works to choose the point at which the grenade is 'let go' from the `tag_weapon` point. As discussed previously, it isn't a bug because I won't be making things appear or move in places they shouldn't be. If you don't want to hit a wall, don't leave your weapon behind one - it's an intentional design decision and strategy because you'll notice the problem doesn't exist on the left side of the screen.

**Comment by shirepirate** [comment]
i don't really think it's fair to not call it a bug, as projectiles getting stuck in a wall to the right of the player is not where they should be at all. it's been a cause of annoyance mentioned by several different people over the course of a couple years before this issue was made (whenever you brush against a wall when throwing a grenade, it sticks).

the "weapon" in this instance, the player's hand holding the grenade, is never behind actual geometry, so this assessment is just plain wrong. if this is intended behavior then the behavior needs to change somehow.

should another issue be created to fix how 3rd person hitbox collision works? why is it different in practice from 1st person anyway? why is it causing problems for grenade & sword?

**Comment by qreeves** [comment]
That's because the animation is different from the first person view. RE does *everything* based on the actual bones and tags on the models. The only way to address the issues is to fix the animations, not the code.

I've said previously that third person is not officially supported, it exists only for those who demanded it and I would rather not have it at all because of the above-mentioned issues, and I believe it is a hack to see more than everyone else.

Third person views are also purposely degraded versions due to the fact you see multiples of them in the scene (other players etc) and we don't really have a LOD system (arenas are small, so it isn't that useful in an FPS).
