### ISSUE TITLE
Auto sendmap only with highest revision

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#469]
It's happening regularly. I'm voting one of my maps and someone else has the older version of it and for some reason server decides to crc lock to that map. I think server should query all players for map revision and then crc lock to the map with highest revision number.

**Comment by shirepirate** [comment]
a /crclocktype could be added, but this would rely on the server being able to obtain the map from a player and thereafter distributing it to all other players (which is bound to take longer, and may not even be successful).

also there's no surefire way to prevent map hacking this way, and the faulty map being distributed to everyone (unless it had a way of checking for most recent valid CRC from the master server).

**Comment by freezurbern** [comment]
Isn't sending the highest revision always going to defeat the goal of crclocking (fighting against map hacking)?

Bill has v1 (not yet updated), Jessie has v2 (actual current release map), Ronda has v2, Katie has v3 (map hacking)

In that situation the server should use v2. But does it have knowledge of which is best (what shirepirate was talking about)? Picking the highest, v3, sounds like a less than ideal design choice to me.

**Comment by pocak100** [comment]
I think FaTony is referring to maps under development, where the server doesn't have a copy. In this case, the server will take the CRC from the first client who reports having the map, i.e. the one with the fastest computer. (At least, in stable.) This is fine when there's only one version of a map in the wild (think old race maps), and results in the least waiting time, but when faced with multiple versions, a more refined algorithm would be nice.

I support FaTony's solution, but here's an alternative: choosing the CRC of the person who proposed/voted first for the map. Perhaps this is easier to implement.

Neither solution would prevent a malicious player from getting everyone onto a defaced map (again, only if the server doesn't have the map), but could help well-meaning people avoid sending the wrong version.

**Comment by qreeves** [comment]
In `master`, it asks for the map from someone who's map CRC has the most number of matches with other clients on the server. Using the highest revision is not a solution.

**Comment by bonifarz** [comment]
Maybe another thing that would help @FaTony is an admin command to force your own map revision, since the /sendmap map command is deprecated?

**Comment by qreeves** [comment]
Yeah, that's why I reopened it.

**Comment by FaTony** [comment]
Again, IF the server doesn't have the map, get map revisions from everyone and crc lock on the guy with the latest revision. This should work.

**Comment by qreeves** [comment]
The problem is, who's to say who's revision is *really* the latest by *the map author*? Anyone could grab a map and modify it, thus creating a newer revision, which is why the server chooses the *most popular* CRC (that meaning, more people have that particular version, so it wins by consensus). Sure, you could let the first person who voted for it be the decider, but who's to say they aren't malicious either? You'd have to restrict it to moderators (which might be OK seeing as you can't vote for maps not in the rotation otherwise). I haven't really heard any sound suggestions that aren't riddled with holes to abuse though.

**Comment by FaTony** [comment]
Honestly, the game is so much open to abuse that I don't get why suddenly this issue seem contentious. All clients should get the same version anyway and malicious entity will abuse the client side movement and hit detection.

**Comment by shirepirate** [comment]
if this issue is for maps under development, and voting some custom map in edit or race mode, then the server should grab the map from the player who first voted for the map, if that is not the current behavior.

but highest revision number is not safe or efficient or a good idea and would circumvent why we created crclock in the first place.

**Comment by FaTony** [comment]
First vote crclock is also a good solution.

**Comment by shirepirate** [comment]
>First vote crclock is also a good solution.

sure, but it can't be that way all the time or the same issue will happen. it can only be first vote when the string is not found in /allmaps

**Comment by graphitemaster** [comment]
I mean you could shove a timestamp into the map format which goes purely by server time. The latest revision is which ever has the larger timestamp. That shouldn't be too difficult. Just use the good old UNIX time. That is consistent across all timezones and what not. You can even prevent against obviously bullshit time stamps, e.g when they're greater than the current time.
