### ISSUE TITLE
Flag to ignore model translation in model preview

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#477]
Vanity items and stuff use model translation (`mdltrans`) to position at a specific spot but does not really work when rendering a model preview frame, a flag should be added to allow ignoring of the translation.

**Comment by bonifarz** [comment]
Nice, so guimodelpreviews ignores the translation now per default, right?
Just checked the vanity previews, as I hoped this simple trick will fit for all of them.
Works fine on many vanities, with a bunch of exceptions, like shoulder2 and prongs.

**Comment by qreeves** [comment]
Yeah, I can make the flag user-facing if really necessary (but I'm not sure it's needed). It's hard to fix models with the translation baked in to the file, maybe a new issue for extending modelpreview to allow specifying offsets? ..though that'd be a pain to manage as well.

**Comment by bonifarz** [comment]
Of course, that's why I said from the beginning that the vanity preview is just an experiment and likely not worth the effort. If i find a simple quick fix that makes it look nice, I'll keep it in the profile menu, otherwise I'll just comment it out again. No problem. But thanks for this FR here, I think it was worth a try :smiley:
