### ISSUE TITLE
scroll cursor issue

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#483]
this one may be more a matter of opinion, though very few have had the chance to experience it yet so perhaps some input will help. the cursorinput texture is now a different size (and placement) than the cursorhover texture. this is not ideal at all (personally i hate it) and can make it more difficult to accurately adjust a scroll bar or select a fill bar option. before it was the same size, and this was easy and intuitive. now it seems clunky and difficult to control. can we make the textures the same size again?

**Comment by qreeves** [comment]
It's actually because, like most operating systems and user interfaces, the cursor switches to a "I" bar when over input fields and in this case the cursor is actually drawn with the center of the image being the hot point instead of the top left corner. The image is the same size but it really doesn't look like an "I" bar (note: the new cursors are programmer art) and I guess it isn't obvious the arrow is still pointing to the hot spot, it's just in a different location.

That being said, it probably isn't useful to use that cursor type on a slider anyway, it's for text input.
