### ISSUE TITLE
Separate out /spectator to swap the arguments for sanity

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#508]
Atm `/spectator` is `/spectator <mode> [<cn>]`, which is backwards to all the other moderation related commands and others (where cn is always first).

Separate it out for UI stuff that uses and mod sanity.

**Comment by bonifarz** [comment]
So, you want two separate commands for users to spectate and for moderators to force spectator state? A */quarantine* command comes to mind, since that's the usual moderation action with the spectator command. If */spectator* was a user command only, one argument would be enough, or maybe even none to toggle.

**Comment by JeffBobbo** [comment]
Pretty much, I mentioned it on IRC last night and quin asked me to make a ticket.

Although mods/people sometimes use spectator to kick out AFK players from games without quarantining people.

**Comment by bonifarz** [comment]
Ah, I see. So, it is probably best to leave */spectator* for moderation, and to introduce a new command (or simply an alias), which could be something like */spectate*, with the corresponding default binds.

Concerning "UI stuff ... and mod sanity", did you know we have a semi-official menu for moderation (client gui)?

**Comment by bonifarz** [comment]
I see there's also a 'spectate' command for convenience now, nice: c2407f751bdabbaaaa8299347da72558922008e1
