### ISSUE TITLE
Losing connection with the server during ALT+TAB

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#551]
So I'm playing on a server, ALT+TAB for a couple of seconds and when I switch back, I lose connection.

**Comment by freezurbern** [comment]
I would like to note, this doesn't happen on Win64 stable for me with Win10 & NVIDIA GeForce GTX 760.

**Comment by pocak100** [comment]
I can confirm on Linux. Probably SDL's fault.

Checking what it's doing after alt-tab: (edited for clarity)
```
^Z
Thread 1 "redeclipse_linu" received signal SIGTSTP, Stopped (user).
0x00007ffff5ea04fd in nanosleep () from /usr/lib/libc.so.6
(gdb) bt
#0  nanosleep () from /usr/lib/libc.so.6
#1  SDL_Delay_REAL at SDL/src/timer/unix/SDL_systimer.c:211
#2  X11_SetWindowGrab at SDL/src/video/x11/SDL_x11window.c:1459
#3  SDL_SendWindowEvent at SDL/src/events/SDL_windowevents.c:167
#4  SDL_SetKeyboardFocus at SDL/src/events/SDL_keyboard.c:648
#5  X11_DispatchFocusIn at SDL/src/video/x11/SDL_x11events.c:375
#6  X11_DispatchEvent at SDL/src/video/x11/SDL_x11events.c:707
#7  X11_PumpEvents at SDL/src/video/x11/SDL_x11events.c:1375
#8  SDL_PumpEvents_REAL at SDL/src/events/SDL_events.c:399
#9  SDL_WaitEventTimeout_REAL at SDL/src/events/SDL_events.c:434
#10 SDL_PollEvent_REAL at SDL/src/events/SDL_events.c:416
#11 pollevent at engine/main.cpp:498
#12 checkinput () at engine/main.cpp:569
#13 main (argc=<optimized out>, argv=<optimized out>) at engine/main.cpp:1044
```

`X11_SetWindowGrab` doesn't return until I click RE on the taskbar. Thus, the game logic doesn't run, and the network isn't pumped, so the connection times out.

This seems to only happen when RE is minimized while it has the mouse grabbed. Alt-tabbing out of the game minimizes it, despite the SDL hint to the contrary in `engine/main.cpp:972`, so the bug is triggered.
If I use a global shortcut to switch to another application (freeing the mouse), then minimize RE using the taskbar icon without moving the mouse over RE's window, then there's no problem.
Also, alt-tab in fullscreen is ok somehow.

**Comment by FaTony** [comment]
I lost connection in fullscreen mode.

**Comment by qreeves** [comment]
What version of SDL2 have you got installed? Their stable release is significantly behind and I was warned about problems on Linux with those versions.

**Comment by FaTony** [comment]
2.0.4-dfsg2-1

**Comment by pocak100** [comment]
For the above testing, I compiled the development version from mercurial to get debugging symbols. Now I did a quick test with v2.0.4 from the Arch repo, and it's the same.

**Comment by qreeves** [comment]
> For the above testing, I compiled the development version from mercurial to get debugging symbols.

You mean for SDL2? As it has been pointed out, it is SDL doing the blocking, not RE. I don't think this is fixable by us without ignoring events completely.

**Comment by pocak100** [comment]
Yes, that's what I meant. There's really not much we can do except wait for SDL2 folks to fix this.

**Comment by graphitemaster** [comment]
Can we get a backtrace that is not of a release build. It's really hard to make head or tails with regard to these things when all the variables are optimized away. Anyways I've traced this myself down into the following SDL2 code

```
/* ICCCM2.0-compliant window managers can handle fullscreen windows
   If we're using XVidMode to change resolution we need to confine
   the cursor so we don't pan around the virtual desktop.
 */
oldstyle_fullscreen = X11_IsWindowLegacyFullscreen(_this, window);

if (oldstyle_fullscreen || grabbed) {
    /* Try to grab the mouse */
    for (;;) {
        int result =
            XGrabPointer(display, data->xwindow, True, 0, GrabModeAsync,
                         GrabModeAsync, data->xwindow, None, CurrentTime);
        if (result == GrabSuccess) {
            break;
        }
        SDL_Delay(50);
    }
...
}
```

When the window manager is not reporting a new enough version or the input needs to be grabbed, SDL will indefinitely try and grab the mouse from X and delay for 50 milliseconds every single iteration until `XGrabPointer` succeeds. This is actually perfectly acceptable behavior and is even documented. The problem here is the engine. Specifically `checkinput` should not be called when there is no focus.

**Comment by graphitemaster** [comment]
Some further investigation shows that is already handled in a round about way, the problem is there is no check to do the same thing when the window is minimized

**Comment by graphitemaster** [comment]
The following patch appears to solve the problem here
```c++
 void checkinput()
 {
+   if (minimized) return;
    SDL_Event event;
    //int lasttype = 0, lastbut = 0;
    bool mousemoved = false, shouldwarp = false;
    while(events.length() || pollevent(event))
 {
```

**Comment by graphitemaster** [comment]
Can we get some others to test this?

**Comment by qreeves** [comment]
Add it to master and see?

**Comment by pocak100** [comment]
Thanks for looking into this. Unfortunately, the patch above doesn't help for me. I'll see if I can investigate more next week.
