### ISSUE TITLE
Random map is not always random

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#570]
On my server when I vote for DM on random map, the server always chooses Castle.

Here's the config:

sv_allowmaps "castle rooftop trainyard docks mirrors chinatown spacestation train flood bridge"
sv_mainmaps "castle rooftop trainyard docks mirrors chinatown spacestation train flood bridge"
sv_gladiatormaps "train flood"
sv_capturemaps "rooftop trainyard docks mirrors chinatown spacestation train bridge"
sv_defendmaps "castle rooftop trainyard docks mirrors chinatown spacestation train flood bridge"
sv_kingmaps "castle rooftop trainyard docks mirrors chinatown spacestation train flood bridge"
sv_bombermaps "rooftop trainyard docks mirrors chinatown spacestation train bridge"
sv_holdmaps "castle rooftop trainyard docks mirrors chinatown spacestation train flood bridge"
sv_racemaps "train"
sv_multimaps "rooftop trainyard docks mirrors train bridge"
sv_duelmaps "castle rooftop trainyard docks mirrors chinatown spacestation train flood bridge"

**Comment by zaquest** [comment]
I think this is because of `sv_smallmaps`, `sv_mediummaps`, `sv_largemaps` and/or related `sv_smallmapmax`, `sv_mediummapmax`, `sv_largemapmax` default values. Server tries to choose maps according to a number of players online. Since `castle` and `rooftop` are the only official maps in that config and they're in `sv_smallmaps` and `sv_mediummaps` respectively, it makes server always choose `castle` when there're less than `sv_smallmapmax` (6 by default) players and `rooftop` when there're less than `sv_mediummapmax` but more than `sv_smallmapmax` players. Server also tries sizes in the order from small to large, so if for example you remove `castle` from `sv_mainmaps` in the config above, it will alway result in `rooftop` for DM random vote. It tries a completely random map only when it fails to choose a map from `sv_<size>maps` variables. So one solution to this is to set all `sv_<size>maps` to empty values, and the other is to assign sizes to you maps.

**Comment by FaTony** [comment]
Ah, that seems to fix it.
