### ISSUE TITLE
Lots of bugs caught by CppCheck

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#574]
So I'm trying more tools to see how horrible the code actually is, here's a batch caught by CppCheck:

[src/engine/blob.cpp:674]: (error) Null pointer dereference: ptr
[src/engine/blob.cpp:675]: (error) Null pointer dereference: ptr
[src/engine/blob.cpp:676]: (error) Null pointer dereference: ptr
[src/engine/command.cpp:2498]: (error) syntax error
[src/engine/console.cpp:570]: (error) Memory leak: h
[src/engine/console.cpp:996]: (error) Memory leak: h
[src/engine/decal.cpp:283]: (error) Null pointer dereference: ptr
[src/engine/decal.cpp:284]: (error) Null pointer dereference: ptr
[src/engine/decal.cpp:285]: (error) Null pointer dereference: ptr
[src/engine/grass.cpp:309]: (error) Null pointer dereference: ptr
[src/engine/grass.cpp:310]: (error) Null pointer dereference: ptr
[src/engine/grass.cpp:311]: (error) Null pointer dereference: ptr
[src/engine/grass.cpp:312]: (error) Null pointer dereference: ptr
[src/engine/octaedit.cpp:1449]: (error) Null pointer dereference: v
[src/engine/octaedit.cpp:1450]: (error) Null pointer dereference: v
[src/engine/skelmodel.h:1299]: (error) Null pointer dereference: vvertbumpws
[src/engine/skelmodel.h:1304]: (error) Null pointer dereference: vvertnws
[src/engine/renderparticles.cpp:744]: (error) Null pointer dereference: ptr
[src/engine/renderparticles.cpp:745]: (error) Null pointer dereference: ptr
[src/engine/renderparticles.cpp:746]: (error) Null pointer dereference: ptr
[src/engine/renderva.cpp:672]: (error) Null pointer dereference: ptr
[src/engine/renderva.cpp:730]: (error) Null pointer dereference: ptr
[src/engine/renderva.cpp:775]: (error) Null pointer dereference: ptr
[src/engine/renderva.cpp:840]: (error) Null pointer dereference: ptr
[src/engine/renderva.cpp:1075]: (error) Null pointer dereference: vdata
[src/engine/renderva.cpp:1861]: (error) Null pointer dereference: ptr
[src/game/client.cpp:1936]: (error) Shifting a negative value is undefined behaviour
[src/game/client.cpp:1947]: (error) Shifting a negative value is undefined behaviour
[src/game/server.cpp:5849]: (error) Shifting a negative value is undefined behaviour
[src/game/server.cpp:5860]: (error) Shifting a negative value is undefined behaviour
[src/game/aiman.h:299]: (error) Array index -1 is out of bounds.
[src/shared/tools.cpp:116]: (error) Shifting a negative value is undefined behaviour

**Comment by pocak100** [comment]
Let's look at one of each type of error.
### [src/engine/blob.cpp:674]: (error) Null pointer dereference: ptr

```c++
        const blobvert *ptr = 0;
        gle::vertexpointer(sizeof(blobvert), ptr->pos.v);
```
False alarm. `ptr` is not actually dereferenced here; if it were, that would cause a segfault.
This is passing to `gle::vertexpointer()` the byte offset of the struct member `pos`, cast as a `void*`. Perhaps using the `offsetof` macro from `<cstddef>` would have been clearer.

### [src/engine/console.cpp:570]: (error) Memory leak: h
The full console history is kept until the game is closed, so there's no code to free the associated memory. IMO not a problem.

### [src/game/client.cpp:1936]: (error) Shifting a negative value is undefined behaviour
This is also given as a warning by clang and gcc (the latter with -Wextra only).
```c++
                    int n = p.get();
                    n |= p.get()<<8;
                    if(flags&(1<<k))
                    {
                        n |= p.get()<<16;
                        if(n&0x800000) n |= -1<<24;
                    }
                    o[k] = n/DMF;
```

A 24-bit value is read from the network and sign extended to fill an int which could be 32-bit or 64-bit wide. I find it elegant; it's unfortunate that it relies on undefined behavior, which can cause issues with future compilers. I recommend `n |= ~0xFFFFFF` as an alternative.

### [src/game/aiman.h:299]: (error) Array index -1 is out of bounds.
```c++
                int plrs[T_TOTAL] = {0}, highest = -1, bots = 0, offset = balance%numt; // we do this because humans can unbalance in odd ways
                if(offset) balance += numt-offset;
                loopv(clients) if(clients[i]->team >= T_FIRST && isteam(gamemode, mutators, clients[i]->team, T_FIRST))
                {
                    if(clients[i]->actortype == A_BOT)
                    {
                        bots++;
                        continue;
                    }
                    int team = clients[i]->team-T_FIRST;
                    plrs[team]++;
                    if(highest < 0 || plrs[team] > plrs[highest]) highest = team;
                }
                if(highest >= 0) loopi(numt) if(i != highest && plrs[i] < plrs[highest]) loopj(plrs[highest]-plrs[i])
                {
                    if(bots > 0) bots--;
                    else balance++;
                }
```
How can -1 be used as an array index here? Or does CppCheck ignore the lazy evaluation of the `||` operator?

---
BTW, this reminds me that once I had a go at RE's code with LLVM's static analyzer, and all but one of its reports I looked at were false positives. Guess I should report that one.

**Comment by IceflowRE** [comment]
Thanks for taking a look at.
But if i see this line.
```
if(highest >= 0) loopi(numt) if(i != highest && plrs[i] < plrs[highest]) loopj(plrs[highest]-plrs[i])
```
I would stop immediately reading the code.....

**Comment by FaTony** [comment]
The code is written in a very cryptic way and my brain segfaults when trying to parse it.

**Comment by FaTony** [comment]
```c++
        const blobvert *ptr = 0;
        gle::vertexpointer(sizeof(blobvert), ptr->pos.v);
```
ptr IS deferenced. This is undefined behavior.

**Comment by q009** [comment]
It's not direct access. That pointer acts at a offset, since it already has a buffer bound
https://www.opengl.org/sdk/docs/man2/xhtml/glVertexPointer.xml

**Comment by pocak100** [comment]
I took dereferencing to mean accessing memory at the pointed to address. `ptr->pos.v` is of type `float[3]`, so the expression just gives a pointer to the first float. I'm no language lawyer, so I don't know if this counts as dereferencing, and it's still undefined behavior anyway. Here's more background on why it's necessary and why it's UB:
http://stackoverflow.com/questions/8283714/what-is-the-result-of-null-int

**Comment by FaTony** [comment]
`ptr->pos.v` can have any value because the internal value of a null pointer is implementation defined. 0 works as a magic number.

**Comment by q009** [comment]
It doesn't read the value, it just reads the offset of 'v' in blobvert.

**Comment by FaTony** [comment]
Which can be anything.

**Comment by q009** [comment]
Of course not, come on, it's basic stuff :P

**Comment by FaTony** [comment]
You just have no idea how C++ works. Using `operator->` on null pointer is undefined behavior, compiler can do absolutely anything. It can format your hard drive, for example.

**Comment by q009** [comment]
Please do some research
https://en.wikipedia.org/wiki/Offsetof

**Comment by FaTony** [comment]
Thanks for providing link that says that you are wrong:

While this implementation works correctly in many compilers, it has undefined behavior according to the C standard,[2] since it involves a dereference of a null pointer

**Comment by pocak100** [comment]
> `ptr->pos.v` can have any value because the internal value of a null pointer is implementation defined. 0 works as a magic number.

That's correct. So what should be done about it? Do you know a better way to use `gl*Pointer`? Or should we avoid VBOs altogether just because they can't be used without relying on undefined behavior?

**Comment by FaTony** [comment]
I haven't found a definition of `gle::vertexpointer`. What's the purpose of the 2nd parameter?

**Comment by pocak100** [comment]
Can't blame you, the overuse of macros makes the code difficult to follow/search. See [glemu.h:78](https://github.com/red-eclipse/base/blob/master/src/shared/glemu.h#L78) *

That 2nd argument is passed directly to `glVertexAttribPointer` as the last argument. See the first answer in my Stack Overflow link above for what `glVertexAttribPointer` does with it.

*kdevelop expands that line to this:
```c++
static inline void enablevertex() { disable() ; glEnableVertexAttribArray_(ATTRIB_VERTEX ); }
static inline void disablevertex() { glDisableVertexAttribArray_(ATTRIB_VERTEX ); }
static inline void vertexpointer(int stride, const void *data, GLenum type = GL_FLOAT , int size = 3 , GLenum normalized = GL_FALSE ) {  disable() ;  glVertexAttribPointer_(ATTRIB_VERTEX , size, type, normalized, stride, data);  }
```

**Comment by graphitemaster** [comment]
While this *is* technically undefined behavior it works on every major compiler known to man. It's often how `offsetof` is implemented in many standard libraries. The compliant way to do this is with `offsetof`. However compilers like gcc/clang add additional restrictions to `offsetof` to produce error diagnostics when the type used isn't `trivially_copy_assignable`. So if you have something like

```
struct a { int x; };
struct b : a { int y; };
offsetof(b, y); // error: cannot offsetof on type which inherits
```

To avoid these compiler errors and warnings, a common idiom is to take a null pointer
of the type you're trying to get the offsetof a field of and dereference it in the context of a constant expression.

The reason it's undefined is because the standard does not have rules governing constant expressions involving pointer types, most compilers support it because it's generally easy to do.

Taking an older C compiler (e.g the one in the last offical UNIX release or Plan9) which are single pass compilers (can't even do constant folding.) this code actually gets evaluated at runtime and causes a segmentation fault.

**Comment by FaTony** [comment]
So, can't it just be fixed of `offsetof`?

**Comment by pocak100** [comment]
Well, `offsetof` gives a `size_t` and OpenGL needs a `void *`, and that cast is also undefined behavior.

I thought the current approach is unsightly, but @graphitemaster calls it a "common idiom", so at this point I don't feel that it needs changing.

**Comment by FaTony** [comment]
Maybe use `offsetof` and then `reinterpret_cast`?

**Comment by qreeves** [comment]
TBH, I don't understand much of this at all. @graphitemaster is in a better position to understand what @lsalzman intended with the code as he has worked with us for a long time. "If it isn't broken, don't fix it"?

**Comment by graphitemaster** [comment]
It's pretty straight forward actually. There are attributes associated with vertex data, e.g texture coordinates, normals, tangents, etc. This information is supplied to OpenGL interleaved, that is you have a structure like:
```
struct vertex {
  vec3 position;
  vec2 uv;
  vec4 tangent;
};
```

The implementation needs to know the relative offset (from the base of the structure) where it may find that information (their type and how many there are) so for instance `tangent` is 5 floats away in the structure. So you could write that as `(void *)(sizeof(float[5]))` but that looks ugly and is likely to lead to bugs if the structure ever changes.

The standard practice is to use `offsetof` from `<stdlib.h>` which is literally implemented as `(size_t)(&((T*)0)->MEMBER)` in a lot of implementations. The reason this works is because the compiler does not actually compile the code into loading zero to a register, dereferencing it at some offset and asking for the address of that. It has constant-folding and other optimizations up its sleeve that eliminate it long before that can occur. Similarly, because it was standard practice to implement `offsetof` that way and lots of code did it anyways, most compilers make a special exception for this to not break code.

Anyways the code here does the same thing, except it's just done directly without the macro, e.g:

```
vertex *p = 0;
&p->tangent
```

Gets us the same result as the example above. I actually think it looks nicer for two reasons, if you do the manual arithmetic like I did above you have to cast the result to `void *` since that is what OpenGL wants. If you use the `offsetof` you have to as well since it returns `size_t`. This code, because it just grabs an address from the field, it already has pointer type and implicitly works with anything taking `void *` like `memcpy`'s src/dest pointers.

Yes it's undefined behaviour in theory, in practice it's so common you're more likely to have perfectly valid code break before this. Especially considering this idiom is so nested in C/C++'s history (implementation wise) it would be the act of an ignorant compiler to break this.

**Comment by FaTony** [comment]
I don't care about legacy stuff and how undefined behavior produces "correct" results on your platforms. In GNU libc offset is implemented like this:

    #define offsetof(TYPE, MEMBER) __builtin_offsetof (TYPE, MEMBER)

This implementation doesn't rely on undefined behavior.

Anyway, we are talking about 1 bug ot of 32. 32! Someone should go ahead and fix them.

**Comment by lsalzman** [comment]
Inane bikeshedding.

**Comment by FaTony** [comment]
This is not bikeshedding. These are legit bugs. You can't simply close the issue and say that they're not.
