### ISSUE TITLE
RedEclipse minimizes on focus loss (alt-tab)

### ISSUE THREAD

**Issue by Hirato** [red-eclipse/base#586]
I personally find this behaviour INCREDIBLY annoying, so the point that I have set the following inside my .zshrc to prevent it in all SDL2 applications

`export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS="0"`

However, RE appeared to be ignoring this hint.
The cause is lines 619-621 in console.cpp, where the alt-tab combo is explicitly intercepted to minimize the window.

```
    case SDLK_TAB:
        keyintercept(iconify, SDL_MinimizeWindow(screen));
        break;
```

Conversely, this hint is set in main.cpp to inhibit SDL's built-in minimize on focus lost feature when the target system is Linux. main.cpp lines 971-973

```
#if !defined(WIN32) && !defined(__APPLE__)
SDL_SetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, "0");
#endif
```

Suggested resolution: If the minimize on focus loss behaviour is desired, get rid of both the key intercept and the hint; the intercept is redundant if the hint isn't defined.

**Comment by pocak100** [comment]
Some observations:

* The game skips rendering when it's minimized, so it uses very little CPU and no GPU time.

* The hint only minimizes in fullscreen mode, while the current code does it in windowed mode as well.

* I play in fullscreen at a smaller resolution than my desktop. When I switch away from the game, SDL only changes the screen back to my desktop resolution when it minimizes the game. Apparently, both `SDL_MinimizeWindow` and the SDL hint work for this purpose.

* That `SDL_MinimizeWindow` call is the root of issue #551, but, because of the above, I've been (unsuccessfully) looking for a solution that keeps it. (And, I forgot about the SDL hint.)

Overall, I'm very much in favor of @Hirato's suggestion.

It might be over engineering things, but I would also like to see the frame rate limited when the game is out of focus.

Do players on Windows and OSX prefer the current behavior or are they also inconvenienced by the auto-minimization?

**Comment by qreeves** [comment]
Yeah all this stuff changed when we got the upgrade to SDL2, so I'm not really aware of the issue and why it was done yet and will have to look into it more.
