### ISSUE TITLE
Translation Support

### ISSUE THREAD

**Issue by Flionk** [red-eclipse/base#606]
The attractiveness is enhanced by more languages. And its easier to understand all comments in the game for german people.

**Comment by bonifarz** [comment]
As a native German speaker, I am not sure if this makes sense for Red Eclipse.

For single players games, it is perfectly reasonable to provide language support, e.g. using *transifex* to get community driven translations in more languages than you could even think of. *Super Tux Kart* is a good example for this approach. However, this is a multiplayer driven project with English as the main language, while foreign language servers are provided by the community. So, you will quickly find other German speaking players that can give you live support in your native language.

Still, someone could pick up translations as a community project, be it a foreign language page on our wiki, a hardcoded translation of some menus, or setting up a transifex repository.

**Comment by TheLastProject** [comment]
As a side note, I'd personally recommend Weblate over Transifex, having used them both (along with CrowdIn and TranslateWiki, which from my experience are even worse)

On 3 December 2016 10:13:29 CET, bonifarz <notifications@github.com> wrote:
>As a native German speaker, I am not sure if this makes sense for Red
>Eclipse.
>
>For single players games, it is perfectly reasonable to provide
>language support, e.g. using *transifex* to get community driven
>translations in more languages than you could even think of. *Super Tux
>Kart* is a good example for this approach. However, this is a
>multiplayer driven project with English as the main language, while
>foreign language servers are provided by the community. So, you will
>quickly find other German speaking players that can give you live
>support in your native language.
>
>Still, someone could pick up translations as a community project, be it
>a foreign language page on our wiki, a hardcoded translation of some
>menus, or setting up a transifex repository.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/red-eclipse/base/issues/606#issuecomment-264627627

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TheAssassin** [comment]
I agree to @bonifarz. It's not only the questionable sense behind translating the game (actually, every German student (and probably 70+ percent of all students around the world) has to attend English classes, so if a player does not speak the English language well enough, they're probably anyway too young to play the game ;)), but also the fact that we have zero internationalization support at all in the game.

Even using an external library/tool (like GNU gettext or one of those ugly XML based things), one would have to wrap every single string in the game with the translation method which takes a lot of time, and the variable/command help text system would have to be rewritten in order to be translatable.

All this makes me think it's not worth the effort. And after all, the in-game chat language is English anyway.

But yes, if it was supported, the localization process could easily be done using weblate.

**Comment by acerspyro** [comment]
In my opinion, porting Red Eclipse to other languages is just not worth it.

- The community is too small, giving it a language barrier is a terrible idea.
- Most of the text is hard coded, and moving everything to language files would be a huge undertaking that is just not worth it.
- Things break all the time when you support multiple languages, probably tripling our issues with localisation issues alone.

**Comment by acerspyro** [comment]
We have discussed the issue on IRC and have determined that this would not only be impossible to implement properly due to Red Eclipse's flexible nature (think custom obits and such), but this would also add a language barrier between the game developers and the players, which is a terrible thing to do in such a small community.

**Comment by Blueberryy** [comment]
Very sad to read, i thought i can help with russian 😿

**Comment by dc-de** [comment]
> Very sad to read, i thought i can help with russian 😿

As a native german speaker, english is fine for a game like ours. Anyone in the world with education is able to speak and understand english. And there isn't much in the interface to read and understand, it's plain english, anyone can understand it without any higher education. Only if you dig deeper into the console you may need to translate things for yourself if your English level is low.
