### ISSUE TITLE
Mutator to control explosives

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#66]
From http://redeclipse.net/forum/viewtopic.php?f=4&t=604

A mutator to control whether explosives spawn in the arena has been requested by several people.

**Comment by DrAzraelTod** [comment]
as stated in the forum: selecting individual weapons to enable/disable (so deselect rocket/grenade/mine for no-explosives) would be far more flexible (but probably way more complex to implement, if only for the needed UI)

**Comment by qreeves** [comment]
I have already stated that would needlessly complicate map voting; people
have a hard enough time sifting through what is already there. Please stay
on topic with what I have approved for the project.

**Comment by bonifarz** [comment]
Seems reasonable, but will also need 
* a cool icon (i guess this is the hardest part)
* an intuitive mutator name (discuss on the forums?)
* a tooltip (okay, this part is trivial) 
* a section in the help menu (no problem)

**Comment by acz13** [comment]
Bonifarz:
- Probably just a  ⃠  with a grenade inside of it.
- IDK
- Explosives are not allowed
- As you said

**Comment by freezurbern** [comment]
Definitely wishlist, because in my opinion this is something that should be left to server variables. Like was mentioned in IRC, on/off things have traditionally been left as just variables. Tradition fallacy I know, but to me a valid point: why use up a mutator slot (and make that gui even more confusing) just to get rid of explosives that aren't as overpowered anymore?

**Comment by shirepirate** [comment]
personally i'd rather see the addition of more creative mutators than one which simply replaces <i>one</i> variable. if it becomes enough of a thing just remove explosives from medieval and insta, though i'm fairly sure more would be against that than for it.

**Comment by freezurbern** [comment]
> if it becomes enough of a thing just remove explosives from medieval and insta, though i'm fairly sure more would be against that than for it.

Most people, from my perspective, don't want explosives because they're used to the 1.4 ones that do amazing amounts of damage.

**Comment by acz13** [comment]
@freezurbern 

> Most people, from my perspective, don't want explosives because they're used to the 1.4 ones that do amazing amounts of damage.

TBH, the grenades are an amazingly powerful weapon in 1.5. I seriously think that this would be a good idea.

**Note**: Perhaps we could add pre-game variable selection during the vote?

**Comment by freezurbern** [comment]
pre-game variable selection? REALLY? Not only are the variables extremely complicated, most people would end up voting something not-so-enjoyable because they don't have the slightest clue how to use the variables for fun. see: 'suicide weapons' server.
Representing this information in a GUI in a way people could make informed choices would be quite difficult as well. I think this would only complicated the already slightly-unused mutator menu.

**Comment by acz13** [comment]
You have a better solution?

**Comment by freezurbern** [comment]
The current solution is great.

**Comment by acz13** [comment]
(Move this to IRC please)

**Comment by freezurbern** [comment]
servinit.cfg example should be updated as well.
