### ISSUE TITLE
Improve "mdlbb"

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#685]
Currently `mdlbb` only accepts two size parameters, "radius" and "height". Internally there is support for both X and Y radii so it would be helpful for non-matching model dimensions to allow the specification for both.

**Comment by Dziq84** [comment]
While we are at it, implementation of this should take model pivot (center) into consideration, currently setting 'height' in this command, make bounding box bottom start from model pivot to 'up' direction, making another half of the model without any collisions.  So bb height should start from pivot along both vertical directions (+ and -).   It will be ideal if autogenerated bb's could be bigger a little than actual model itself, or if player can't walk that near to bb.   :)    I wrote about pivot because I think it can be missed easily, for some models its better to have pivot on bottom, while on others its better to have it on center.  Cheers

**Comment by qreeves** [comment]
Invalid, use `mdlextendbb`.
