### ISSUE TITLE
Random weapon selection isn't really random

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#689]
So I tend to use the random weapon feature on my secondary slot, and use the filter to limit it to the sword and the shotgun.

Unfortunately, in >80% of all spawns (rough estimation), my secondary is the sword, and only very rarely I spawn with a shotgun instead. This is quite a problem, as it is quite annoying and... kinda... ruins the feature.

We should thus check how the next weapon is chosen. Ideally, a random variable with uniform distribution would be used for this. This means we should probably implement our own algorithm for randomness, as the features provided by C+(++) (without the standard library, to be fair) are very limited (they might be "random", but for our use case, we need something "better").

(Side note: C++11 contains facilities for this, see e.g. [cppreference.com](http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution). I could test that at work, and it was really good at what it promised to do. Unfortunately, some people don't like `std::` (or stuff like `boost::`, where this is implemented, too). 

I'll try to come up with something independent, using the same algorithms.

**Comment by qreeves** [comment]
You've pretty much over-complicated the issue with all these suppositions.

The real factor at play would be that the random call is using the total number of weapons instead of the ones available to it as defined by the filter, so when it is out of range it increments it by one (wrapping at the total number back to the beginning) making it more likely to pick the sword in your specific circumstance.

In your example:
 * You allow weapons 1 and 2.
 * Random uses the total number of loadout weapons to generate a number.
 * The number returned is 3 or more.
 * The function increments by one until it finds an allowable weapon.
 * Ends up wrapping around at the number of loadout weapons back to the beginning
 * The result is a higher chance of picking the first weapon allowed by the filter.

But yes, this should be fixed, just not in the way you think.

**Comment by TheAssassin** [comment]
@qreeves yeah we've already discussed this further on IRC, and found that the problem is pretty much what you described instead of what I supposed. The RNG works perfectly fine, I've written some test scripts yesterday to check that, and the showed a nearly perfect uniform distribution.

Though, in most cases where issues like this have been found before, it was caused by a poor random number generator. It isn't that odd to think of that first.

I've found the relevant code yesterday night already in `tools.h`. I'll create a PR.
