### ISSUE TITLE
Updater scripts use brace completion in module prefetch url, incompatible with all but curl.

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#724]
This currently only affects *nix without curl installed, although the root issue is present everywhere (including the windows batch file). When the updater tries to download the files from the variable `REDECLIPSE_MODULE_PREFETCH`, it will fail due to wget not understanding the brace syntax used to match multiple files in one command.

This affects both stable and master.

**Comment by TheAssassin** [comment]
The problem has probably nothing to do with wget itself, but with the shell the script is run with. Bash allows a lot more constructs which are invalid in other shells, such as dash which is Debian's default. I'd suggest to either try to find a version without braces, or alternatively use the `printf` command to populate the variable.

**Comment by shacknetisp** [comment]
The shell has nothing to do with the issue, curl understands brace completion, wget does not. The `{list,of,files}.txt` is passed as a command-line argument, braces included. It will be easy to replace it with real multiple arguments (or a loop, even).

**Comment by qreeves** [comment]
It used to be a loop, but using this method with curl makes it so the connection is kept open between GET requests, rather than it being shut down and reconnected. I'm more inclined to remove wget as a backup as it doesn't support quite a few features.

That being said, it's not worth putting too much effort into this. The scripts were a proof of concept and the end goal is to have a proper updater.
