### ISSUE TITLE
All client data should be in .redeclipse for "linux" client

### ISSUE THREAD

**Issue by PyroSamurai** [red-eclipse/base#727]
May be a partial duplicate of #531 , not sure since its description was vague as hell.

So, here's my issue: Please move all client data out of `usr/share/games/redeclipse` and into `~/.redeclipse` where it really should be. 

I use a separate partition for my home directory (a common setup supported by all ubuntu gui installers). Therefore I have a small 15gb system partition which is sudo accessible only. Having a game's client data take up a 1gb of that space for client data isn't really ideal. Please remedy this.

(When the system partition is full, I can no longer install new packages or update old ones. I am more willing to remove the game than resize the partitions so don't even suggest that.)

I've been reading the forum for hours to make sure someone didn't mention it. I've removed the game in the meantime and will reinstall when this problem is fixed :)

I searched the issue list and checked that this is not a duplicate :white_check_mark: 
I tried to rename my *config.cfg*, and the problem also occurs with default settings :white_check_mark:

**Comment by qreeves** [comment]
None of our official packages use `/usr/share/games/redeclipse`, typically this is done by whomever creates the distribution specific packages (which we don't officially support due to the modifications and often lack of prompt updates each new release).

By default, our [official install method on Linux](https://redeclipse.net/wiki/How_to_Install_Red_Eclipse#Official_packages) has you unpack the archive into your home directory and keeps everything in place (meaning you delete the "redeclipse-X.Y.Z" directory and "~/.redeclipse" and the game is completely removed).

**Comment by PyroSamurai** [comment]
okay, I'll bring it up with playdeb then. Btw let me know if you ever go for an self-updating package setup like dropbox does. I'll help you code it.

**Comment by TheAssassin** [comment]
I am maintaining a Red Eclipse AppImage. AppImages are completely self-contained, and don't even need to be installed (think of a "portable app" which you could even put on a USB disk and run everywhere).

The AppImage team is beginning to completely rework the updater software within the next 6 weeks. It will then be embeddable into AppImages. You can expect the Red Eclipse ones to be among the first ones which will receive this feature. Otherwise, you can use the legacy AppImageUpdate to manually update the AppImages.

You can find instructions specifically for the Red Eclipse AppImage on our wiki: https://redeclipse.net/wiki/How_to_Install_Red_Eclipse#AppImage

I see many happy users of the AppImage playing frequently, and presume this could be an alternative for you as well. 

By the way, as a package maintainer for Red Eclipse (see that wiki page, I host some OpenSUSE Build Service Debian/Ubuntu repository which is a lot more professional than anything PlayDeb produces...), I can tell you that `/usr/share/games` is the one and only right place for these data. The error is with you having created a way too small `/usr` partiton. See the FHS (filesystem hierarchy standard) documents on Wikipedia and the Debian homepage. It is just impossible to put data shipped by a Debian package into anything like `/home`, and also doesn't make any sense to do so.

**Comment by IceflowRE** [comment]
And you know that `redeclipse.sh`, update the program itself?

**Comment by PyroSamurai** [comment]
@TheAssassin I prefer to follow the "XDG Base Directory Specification" which you can find mentioned at the bottom of debian's FHS page. It states that application data files should be under `~/.local`. Any data inside `/usr` should be limited to what base client itself needs to simply run not things like maps. So my advice is don't ship the data with the client if you can't put it there. Make an update server like every MMO out there.

BUT that is just my opinion. You don't have to subscribe to it, but the same goes for yours.

@IceflowRE Thanks for mentioning that. From reading forum, I believed that that script was still incomplete. Is it considered production-ready now?

**Comment by IceflowRE** [comment]
@PyroSamurai Yes its production ready.

**Comment by TheAssassin** [comment]
The AppImage is production ready, too, and removes all the hassle of having some random directory on your system... Just a clean way to get Red Eclipse.

**Comment by PyroSamurai** [comment]
@TheAssassin I'll give the AppImage a try, it looks like an interesting idea. I certainly wouldn't trust it for any related to the system, but it seems like a decent system for games, companies might even consider supporting a GNU+Linux build because of it.

One question though, it seems to harp on read-only, does that mean no custom maps and other non-official mods are possible?

**Comment by TheAssassin** [comment]
No, it works like a normal application, and will put that data in the `~/.redeclipse` directory.

**Comment by PyroSamurai** [comment]
@TheAssassin Okay, cool. Thanks.
