### ISSUE TITLE
Drones and grunts have the same model on onslaught.

### ISSUE THREAD

**Issue by SniperGoth** [red-eclipse/base#787]
Drones aren't using their own model, and instead use the default playermodel [Development version, tested on last build].

- How to reproduce:
Make a simple map with either drones or grunts actors, then load it on onslaught. Both are using the same model.

Or just load this up : 
[onslaught-tests.zip](https://github.com/red-eclipse/base/files/1583193/onslaught-tests.zip)

![20171222145601](https://user-images.githubusercontent.com/24359960/34308056-6bd3ef50-e732-11e7-921c-bfbe12826a95.png)
Map configured with drones.
![20171222145006](https://user-images.githubusercontent.com/24359960/34308065-8124fdae-e732-11e7-9c86-de51b8376871.png)
Same map, configured to use grunts.

**Comment by qreeves** [comment]
The old actor models have been deprecated due to their poor aesthetic and the fact that the game now relies on various features that have only been implemented in the base model (like tags, etc). They now have different sizes to distinguish the difference.

This won't be fixed unless someone actually creates a quality model for each of the other actor types.

**Comment by SniperGoth** [comment]
Hmn, that explains it. Thanks you for clearing this up ^^
