### ISSUE TITLE
No optimization of slanted surfaces after remipping

### ISSUE THREAD

**Issue by molexted** [red-eclipse/base#795]
Mipped
![20180103180218](https://user-images.githubusercontent.com/23445929/34547524-8af96b62-f0b0-11e7-85f3-2e318f36bbe9.png)

Unmipped
![20180103180213](https://user-images.githubusercontent.com/23445929/34547525-8b166e6a-f0b0-11e7-82ca-482f3666ba98.png)
Remipping does not lower the amount of geometry on slanted panels, leading to low-detail high-geometry surfaces.

Screenshots from 1.9.9 master 2022.

**Comment by qreeves** [comment]
As @lsalzman mentioned on IRC, this is actually the result of `filltjoints`. This is a necessary rendering technique in order to prevent sparklies on certain cards (which is not easy to determine either IIRC). Unless you're familiar with the renderer and the programming involved, it probably doesn't make sense but it is intentional and therefore won't be fixed.
