### ISSUE TITLE
Could not find core textures

### ISSUE THREAD

**Issue by su8** [red-eclipse/base#832]
Prior to launching the game I get:

![2018-07-10-233602_1920x1080_scrot](https://user-images.githubusercontent.com/29376083/42539229-c1acbda2-849a-11e8-98a3-205959e2a440.png)

**Comment by su8** [comment]
>2018-07-10 23:41.16 loading enet..
2018-07-10 23:41.16 loading game..
2018-07-10 23:41.16 version: 1.6.0-nix64-inplace client (Sunset Edition) [0x30e6ca9b]
2018-07-10 23:41.16 loading sdl..
2018-07-10 23:41.16 loading video..
2018-07-10 23:41.16 loading gl..
2018-07-10 23:41.16 renderer: AMD RS780 (DRM 2.50.0 / 4.17.3-gentoo, LLVM 5.0.1) (X.Org)
2018-07-10 23:41.16 driver: 3.3 (Core Profile) Mesa 17.3.9
2018-07-10 23:41.16 could not load texture textures/notexture
could not find core textures

**Comment by su8** [comment]
Same thing with the current stable branch.

**Comment by IceflowRE** [comment]
Since no on other answered yet, i will try my best:
1. for such "help" questions better use https://github.com/red-eclipse/world/issues/
2. Please provide informations like OS and what did you do (did you updated from a previous version, clean installation, from where do you have the installer?)

To the problem:
The `core textures` are inside `data/textures` and it looks like they are not downloaded/ existing.
I would suggest that you backup (in case you have something like an auth saved there) and delete the `/home/frost/.redeclipse` folder, then try again.
If this wont work, download additionally the installer again from https://www.redeclipse.net/download.

If this wont work, we have to look further.

**Comment by Dziq84** [comment]
you can try to delete contents of cache folder in Home folder, then run updater again

**Comment by su8** [comment]
Thank you for the suggestions, but none of them worked.

**Comment by su8** [comment]
Those are the downloaded files in my cache, moved the 1.6 files in another folder since I'm currently using the stable branch.

![2018-07-11-143522_814x689_scrot](https://user-images.githubusercontent.com/29376083/42571577-e19f8220-8517-11e8-8327-5359227c0a5a.png)

**Comment by qreeves** [comment]
I'm not sure if it makes a difference, but try using `./redeclipse.sh` instead of `bash redeclipse.sh`

Other than that, we'll need more information about what you're actually doing, step by step starting with a fresh install, along with your operating system information.

**Comment by su8** [comment]
Managed to solve it by recompiling **sdl2-image** with the following USE flags:

>sudo USE="gif jpeg png tiff" emerge -a media-libs/sdl2-image

**Comment by qreeves** [comment]
Thanks for the update, it helps with future support requests.
