### ISSUE TITLE
Steam beta branch

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#895]
As we gonna publish this game on steam, it would be a nice addition aside of using the `stable` branch as the normal game, to add the `devel` branch as a beta branch.
https://partner.steamgames.com/doc/store/application/branches

**Comment by qreeves** [comment]
![image](https://user-images.githubusercontent.com/3297929/62037779-ca63e300-b237-11e9-8988-87b2abf05940.png)
:smile:

**Comment by IceflowRE** [comment]
Welp -.- MB

**Comment by IceflowRE** [comment]
You are right, but i was more about normal = stable and devel = beta, currently both are devel.
But i guess that implies more changes to the stable branch? I meant more that we should not forget about that.

**Comment by qreeves** [comment]
Normal should be v1.6, and devel should be v1.9.9 already?

**Comment by IceflowRE** [comment]
No, if i install RE over steam i get the 1.9.9 and if i switch to `devel` beta branch i get 1.9.9 too.

**Comment by qreeves** [comment]
Oh yes, you're absolutely right. I never ported it back to stable because there's no intention to make it work with Steam. The normal branch has to be updated manually through the Steam partner interface, whereas other branches can be pushed automatically by the deploy script. In the end, it will be stable/devel though once v2.0 is released.
